coverage:
  status:
    project:
      default:
        enabled: true
        target: 100
        threshold: 1%
        branches:
          - "main"

comment:                  #this is a top-level key
  layout: " diff, flags, files"
  hide_project_coverage: false
