on: ["push", "pull_request"]

name: Test CodeCov

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4


      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies and test
        run: |
          yarn install --no-immutable
          yarn build
          yarn test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: velgersdyk25/carbon-coverall-poc
